{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "OpenSSL",
                    "vendor": "OpenSSL",
                    "versions": [
                        {
                            "lessThan": "1.0.2n",
                            "status": "affected",
                            "version": "1.0.2b",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "David Benjamin (Google)"
                }
            ],
            "datePublic": "2017-12-07T00:00:00Z",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "OpenSSL 1.0.2 (starting from version 1.0.2b) introduced an \"error state\" mechanism. The intent was that if a fatal error occurred during a handshake then OpenSSL would move into the error state and would immediately fail if you attempted to continue the handshake. This works as designed for the explicit handshake functions (SSL_do_handshake(), SSL_accept() and SSL_connect()), however due to a bug it does not work correctly if SSL_read() or SSL_write() is called directly. In that scenario, if the handshake fails then a fatal error will be returned in the initial function call. If SSL_read()/SSL_write() is subsequently called by the application for the same SSL object then it will succeed and the data is passed without being decrypted/encrypted directly from the SSL/TLS record layer. In order to exploit this issue an application bug would have to be present that resulted in a call to SSL_read()/SSL_write() being issued after having already received a fatal error."
                }
            ],
            "metrics": [
                {
                    "format": "other",
                    "other": {
                        "content": {
                            "text": "Moderate"
                        },
                        "type": "https://www.openssl.org/policies/secpolicy.html#moderate"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "Unauthenticated read/unencrypted write",
                            "lang": "en"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "b3476cb9-2e3d-41a6-98d0-0f47421a65b6",
                "shortName": "openssl"
            },
            "references": [
                {
                    "name": "OpenSSL Advisory",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://www.openssl.org/news/secadv/20171207.txt"
                },
                {
                    "name": "1.0.2n git commit",
                    "tags": [
                        "patch"
                    ],
                    "url": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=898fb884b706aaeb283de4812340bb0bde8476dc"
                }
            ],
            "title": "Read/write after SSL object in error state",
            "x_generator": {
                "importer": "vulnxml2json5.py 2022-11-04 07:19:07.043222"
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "b3476cb9-2e3d-41a6-98d0-0f47421a65b6",
        "cveId": "CVE-2017-3737",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}